### ISSUE TITLE
Primary (mis)fire

### ISSUE THREAD

**Issue by sudobbq** [InsanityBringer/ChocolateDescent#16]
**Symptom:**  
Primary fire ignores joystick input or primary fire holds down joystick input

**Detailed symptom:**
When playing through the levels like normal, my ship wouldn't fire the lasers when I would click the trigger.  It would work the second time I click the trigger.   The other symptom is it acted like it was held down until I clicked the trigger a second time.  

**Device:**  
Logitech Extreme 3d pro joystick (USB)

**Issue Reproduceable?**  
Common, but not at will.

**Is it a Joystick issue:**  
No, the symptom does not exist on any other game and it is virtually brand new (used for about 4 hours)

**OS**
Windows 11

**Comment by InsanityBringer** [comment]
This is confirmed to be a SDL bug. All future releases will ship SDL 2.0.20 to avoid it.
