### ISSUE TITLE
Unable to build on Windows 10 (32-bit)

### ISSUE THREAD

**Issue by rzhxiii** [InsanityBringer/ChocolateDescent#20]
I'd like to start this off by saying that I barely have any idea of what I'm doing, since I've never used Visual Studio until I found this project.
I was able to somehow build both Chocolate Decent 1 and 2 a few months ago, but the process was so messy, that I deleted the entire app afterwards, however newer updates made try to attempt it one more time, this time around after gaining some more experience with MSYS2/ MinGW.
Now, however, I'm not able to do it at all.
Here's what I did:

1.  In MinGW

- git clone https://github.com/InsanityBringer/ChocolateDescent
- cd chocolatedescent
- mkdir build; cd build
- cmake -G "Visual Studio 16 2019" ..

So far so good, but I did have to add to the CMake cache the paths to SDL, Fluidsynth and OpenAl manually and re-run the cmake command.
Afterwards, I open Visual Studio 2019, and whatever I try, I always run into stuff like this:
![Capture](https://user-images.githubusercontent.com/82729328/163692802-69ad510a-fa57-4868-bcad-c0185b72d774.PNG)

Since I assume getting over 12000 errors and a few thousands warnings is definitely something unusual, I can only attribute this to a lack of experience on my part.
Are there certain options that need to be toggled/ pre-requisites that need to be installed/ things that I'm missing?
I would really like more detailed build instructions and I apologize if this turns out to be a headache.
Good thing is that I've finished Descent 1 with an older build and I didn't have any crashes or notice any weird behaviour.
Descent 2 did crash a few times and there were some graphical glitches, but I'm not sure if those also show up in vanilla.
Overall, I really like this port, and hopefully someday it gets the attention it deserves and maybe a "Crispy" treatment.

**Comment by InsanityBringer** [comment]
I'm not really able to comment on this ATM, since I have no experience building it from the CLI using MSYS 2 (when I try, CMake fails on the grounds that the self-contained CMake installation installed with pacman lacks the Visual Studio generators.)  I always run CMake from either the GUI version or the Windows console. 

If it's desired, given that compiling with GCC is possible on Linux, I can look into fixing any build errors with MinGW's gcc port to make the experience more smooth for those using Mingw/MSYS 2

**Comment by rzhxiii** [comment]
Ok, I am now able to build the .exes, but something is still wrong.
The .exes are the debug versions I assumed, since I can change the music and play any level from the menu.
Also, way too many .dlls need to be in the same folder for the .exe to launch.
I assume they don't get statically linked (?) if that's the term.
Again, I'm barely a novice, I can only compile some stuff successfully.
I tried looking at CMakeLists.txt, but I'm not sure how I can select the release version of the .exe or statically link all shared libraries.
