### ISSUE TITLE
None of the Chocolate Menu settings actually stick

### ISSUE THREAD

**Issue by rzhxiii** [InsanityBringer/ChocolateDescent#22]
First of all, glad to see you back, I really, really like this port.
I've tried out the Chocolate Menu settings, but none of them actually seem to stick.
Fullscreen/ Window Size and MIDI settings kinda work, but only for that particular session, if you close the game and re-open it, then the settings revert to default.
This happens even if the app is run with Admin rights and if the chocolatedescent.cfg file is deleted.

**Comment by InsanityBringer** [comment]
Fixed in beta 0.3

**Comment by rzhxiii** [comment]
No worries, Rome wasn't built in a day.
